version: "3.7"
services:
  app:
    build:
      context: .
    image: node-app:latest # Explicitly set the image name
    container_name: node-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
