apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
type: Opaque
data:
  DATABASE_URL: ${DATABASE_URL}
  ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}
  SENDER_EMAIL: ${SENDER_EMAIL}
  NODE_ENV: ${NODE_ENV}
  AMQP_CONNECTION_STRING: ${AMQP_CONNECTION_STRING}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  RABBITMQ_URI: ${RABBITMQ_URI}
