name: Deploy to Google Cloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # If you're storing your secrets securely using GitHub Secrets
      - name: Build Docker images
        run: |
          docker-compose --env-file .env -f docker-compose.yml build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          AMQP_CONNECTION_STRING: ${{ secrets.AMQP_CONNECTION_STRING }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          RABBITMQ_URI: ${{ secrets.RABBITMQ_URI }}

      - name: Push Docker image to registry
        run: |
          docker-compose --env-file .env -f docker-compose.yml push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
